spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/fast_sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
#    driver-class-name: org.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#    open-in-view: false

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080



#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
