spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/fast_sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
#    driver-class-name: org.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
  #    open-in-view: false

#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: debug
#          type: trace

server:
  port: 8080



#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
